#!/usr/bin/env bash
set -euo pipefail

# Tunable FP32 direct-start SST-2003m 500D same-DOF low-y+ remapped-mesh runner for NodalS HXT5B.
# Put this script in hybrid_hxt5b/ OR set HXT5B_DIR to that directory.
SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "$SELF_DIR/RUN_HXT5B.sh" ]]; then
  ROOT="$SELF_DIR"
else
  ROOT="${HXT5B_DIR:-$HOME/Downloads/NodalS_SST_G2_DIRECT_START_FIX1_ad27cce_20260912/gpu/serial_cuda/hybrid_hxt5b}"
fi
[[ -f "$ROOT/RUN_HXT5B.sh" ]] || { echo "ERROR: RUN_HXT5B.sh not found under ROOT=$ROOT"; echo "Set HXT5B_DIR=/path/to/gpu/serial_cuda/hybrid_hxt5b"; exit 2; }

MESH="${MESH:-$HOME/Downloads/NodalS_SST_G2_500D_LOWY_SAME_DOF_20260912/mesh_500D_lowy_gap018/HXT1_mesh_500D_lowy.bin}"
[[ -f "$MESH" ]] || { echo "ERROR: mesh not found: $MESH"; echo "Run BUILD_HXT1_500D_LOWY.sh first, or set MESH=/path/to/HXT1_mesh_500D_lowy.bin"; exit 2; }

# ---- Flow / SIMPLE under-relaxation ----
ALPHA_U="${ALPHA_U:-0.70}"
ALPHA_P="${ALPHA_P:-1.00}"
RAU_SCALE="${RAU_SCALE:-20.0}"

# ---- SST nonlinear equation relaxation ----
SST_ALPHA_K="${SST_ALPHA_K:-0.70}"
SST_ALPHA_OMEGA="${SST_ALPHA_OMEGA:-0.70}"

# ---- Momentum inner solve ----
MOM_WORK="${MOM_WORK:-sgs1}"
MOM_OMEGA="${MOM_OMEGA:-1.0}"
MOM_RTOL="${MOM_RTOL:-0.01}"
MOM_ATOL="${MOM_ATOL:-1e-8}"
MOM_MAX="${MOM_MAX:-50}"
MOM_CAP_POLICY="${MOM_CAP_POLICY:-warn}"

# ---- Pressure PCG ----
PRESSURE_SOLVER="${PRESSURE_SOLVER:-pcg_amg}"
P_RTOL="${P_RTOL:-0.9}"
P_ATOL="${P_ATOL:-1e-12}"
P_MAX="${P_MAX:-50}"

# ---- Pressure AMG hierarchy ----
AMG_HIERARCHY="${AMG_HIERARCHY:-cf}"
CF_COARSENING="${CF_COARSENING:-pmis}"
CF_STRENGTH="${CF_STRENGTH:-classical-negative}"
CF_THETA="${CF_THETA:-0.25}"
CF_INTERP="${CF_INTERP:-exti}"
CF_PMAX="${CF_PMAX:-8}"
CF_AGGRESSIVE_FIRST="${CF_AGGRESSIVE_FIRST:-0}"
AMG_TERMINAL="${AMG_TERMINAL:-1000}"

# ---- AMG smoother: default MCGS ----
AMG_SMOOTHER="${AMG_SMOOTHER:-mcgs}"
AMG_MCGS_FINE_SWEEPS="${AMG_MCGS_FINE_SWEEPS:-2}"
AMG_MCGS_COARSE_SWEEPS="${AMG_MCGS_COARSE_SWEEPS:-2}"
AMG_MCGS_OMEGA="${AMG_MCGS_OMEGA:-1.0}"
AMG_MCGS_ORDER="${AMG_MCGS_ORDER:-symmetric}"
# Kept exposed for switching back to Jacobi/Cheb without another wrapper.
AMG_JACOBI_OMEGA="${AMG_JACOBI_OMEGA:-0.7}"
AMG_JACOBI_FINE_SWEEPS="${AMG_JACOBI_FINE_SWEEPS:-1}"
AMG_JACOBI_COARSE_SWEEPS="${AMG_JACOBI_COARSE_SWEEPS:-1}"
AMG_CHEB_DEGREE="${AMG_CHEB_DEGREE:-6}"
AMG_POWER_ITS="${AMG_POWER_ITS:-16}"
AMG_LAMBDA_SAFETY="${AMG_LAMBDA_SAFETY:-1.5}"
AMG_LAMBDA_LOW_FRACTION="${AMG_LAMBDA_LOW_FRACTION:-0.05}"
AMG_SPECTRUM_POLICY="${AMG_SPECTRUM_POLICY:-auto}"

# ---- k/omega SGS inner solves ----
SST_LINEAR_RTOL="${SST_LINEAR_RTOL:-0.20}"
SST_LINEAR_ATOL="${SST_LINEAR_ATOL:-1e-7}"
SST_LINEAR_MAX="${SST_LINEAR_MAX:-12}"
SST_GS_OMEGA="${SST_GS_OMEGA:-1.0}"

# ---- Physical / SST setup ----
RE="${RE:-13691.740248127866}"
BULK="${BULK:-50.0}"
SST_INTENSITY="${SST_INTENSITY:-0.05}"
SST_LENGTH_RATIO="${SST_LENGTH_RATIO:-0.07}"
SST_K_FLOOR="${SST_K_FLOOR:-1e-8}"
SST_OMEGA_FLOOR="${SST_OMEGA_FLOOR:-1e-3}"
SST_WALL_PENALTY_GAMMA="${SST_WALL_PENALTY_GAMMA:-50}"
SST_OMEGA_WALL_MODE="${SST_OMEGA_WALL_MODE:-of_auto}"
WALL_SAMPLE_FRACTION="${WALL_SAMPLE_FRACTION:-0.5}"
MOM_NITSCHE_GAMMA="${MOM_NITSCHE_GAMMA:-${GAMMA:-50}}"
SCHUR_NITSCHE_GAMMA="${SCHUR_NITSCHE_GAMMA:-0}"

# ---- OpenFOAM-informed automatic wall treatment ----
SST_OF_KAPPA="${SST_OF_KAPPA:-0.41}"
SST_OF_E="${SST_OF_E:-9.8}"
SST_OF_BETA1="${SST_OF_BETA1:-0.075}"
SST_OF_RE_BLEND="${SST_OF_RE_BLEND:-11.0}"
SST_OF_PRODUCTION="${SST_OF_PRODUCTION:-1}"
SST_OF_PRODUCTION_SCALE="${SST_OF_PRODUCTION_SCALE:-1.0}"
SST_OF_WALL_VOLUME_SCALE="${SST_OF_WALL_VOLUME_SCALE:-1.0}"
SST_OF_PRODUCTION_LIMIT="${SST_OF_PRODUCTION_LIMIT:-10.0}"

# ---- Coupled outer iteration / plateau ----
SST_G2_MAX="${SST_G2_MAX:-800}"
SST_G2_PRINT_EVERY="${SST_G2_PRINT_EVERY:-20}"
SST_G2_PLATEAU_TOL="${SST_G2_PLATEAU_TOL:-2.5e-3}"
SST_G2_PLATEAU_SAMPLES="${SST_G2_PLATEAU_SAMPLES:-5}"
MAX_OUTER="${MAX_OUTER:-1200}"
SIMPLE_TOL="${SIMPLE_TOL:-4e-3}"
OUTER_CONT_ATOL="${OUTER_CONT_ATOL:-1e-12}"

TAG="${TAG:-sst_g2_500D_lowy_ofauto_gap018_mcgs_prtol${P_RTOL}_au${ALPHA_U}_ap${ALPHA_P}_ak${SST_ALPHA_K}_ao${SST_ALPHA_OMEGA}}"
TAG="${TAG//./p}"
OUT="${OUT:-$ROOT/results_${TAG}}"
CLEAN_OUT="${CLEAN_OUT:-1}"
if [[ "$CLEAN_OUT" == "1" ]]; then rm -rf "$OUT"; fi
mkdir -p "$OUT"

cat <<CFG
=== SST G2 500D LOW-Y+ OPENFOAM-INFORMED AUTO WALL FP32 ===
ROOT=$ROOT
MESH=$MESH
OUT=$OUT
start=PLUG_POTENTIAL precursorSimpleIterations=0
alphaU=$ALPHA_U alphaP=$ALPHA_P alphaK=$SST_ALPHA_K alphaOmega=$SST_ALPHA_OMEGA rauScale=$RAU_SCALE
momentumNitscheGamma=$MOM_NITSCHE_GAMMA schurNitscheGamma=$SCHUR_NITSCHE_GAMMA
omegaWallMode=$SST_OMEGA_WALL_MODE sstWallPenaltyGamma=$SST_WALL_PENALTY_GAMMA wallSampleFraction=$WALL_SAMPLE_FRACTION
ofAuto kappa=$SST_OF_KAPPA E=$SST_OF_E beta1=$SST_OF_BETA1 ReBlend=$SST_OF_RE_BLEND production=$SST_OF_PRODUCTION productionScale=$SST_OF_PRODUCTION_SCALE wallVolumeScale=$SST_OF_WALL_VOLUME_SCALE productionLimit=$SST_OF_PRODUCTION_LIMIT
momentumWork=$MOM_WORK momentumOmega=$MOM_OMEGA momentumRtol=$MOM_RTOL momentumAtol=$MOM_ATOL momentumMax=$MOM_MAX
pressureSolver=$PRESSURE_SOLVER pressureRtol=$P_RTOL pressureAtol=$P_ATOL pressureMax=$P_MAX
amgHierarchy=$AMG_HIERARCHY coarsening=$CF_COARSENING smoother=$AMG_SMOOTHER
mcgsFineSweeps=$AMG_MCGS_FINE_SWEEPS mcgsCoarseSweeps=$AMG_MCGS_COARSE_SWEEPS mcgsOmega=$AMG_MCGS_OMEGA mcgsOrder=$AMG_MCGS_ORDER
sstScalarRtol=$SST_LINEAR_RTOL sstScalarAtol=$SST_LINEAR_ATOL sstScalarMax=$SST_LINEAR_MAX sstGsOmega=$SST_GS_OMEGA
plateauTol=$SST_G2_PLATEAU_TOL plateauSamples=$SST_G2_PLATEAU_SAMPLES maxG2=$SST_G2_MAX
CFG

PREC=fp32 MESH="$MESH" OUT="$OUT" \
RE="$RE" BULK="$BULK" MIXLEN_SCALE=0.0 WALL_SAMPLE_FRACTION="$WALL_SAMPLE_FRACTION" MOM_NITSCHE_GAMMA="$MOM_NITSCHE_GAMMA" SCHUR_NITSCHE_GAMMA="$SCHUR_NITSCHE_GAMMA" \
MAX_OUTER="$MAX_OUTER" SIMPLE_TOL="$SIMPLE_TOL" OUTER_CONT_ATOL="$OUTER_CONT_ATOL" \
ALPHA_U="$ALPHA_U" ALPHA_P="$ALPHA_P" RAU_SCALE="$RAU_SCALE" \
MOM_WORK="$MOM_WORK" MOM_OMEGA="$MOM_OMEGA" MOM_RTOL="$MOM_RTOL" MOM_ATOL="$MOM_ATOL" MOM_MAX="$MOM_MAX" MOM_CAP_POLICY="$MOM_CAP_POLICY" \
PRESSURE_SOLVER="$PRESSURE_SOLVER" P_RTOL="$P_RTOL" P_ATOL="$P_ATOL" P_MAX="$P_MAX" \
AMG_HIERARCHY="$AMG_HIERARCHY" CF_COARSENING="$CF_COARSENING" CF_STRENGTH="$CF_STRENGTH" CF_THETA="$CF_THETA" CF_INTERP="$CF_INTERP" CF_PMAX="$CF_PMAX" CF_AGGRESSIVE_FIRST="$CF_AGGRESSIVE_FIRST" AMG_TERMINAL="$AMG_TERMINAL" \
AMG_SMOOTHER="$AMG_SMOOTHER" AMG_MCGS_FINE_SWEEPS="$AMG_MCGS_FINE_SWEEPS" AMG_MCGS_COARSE_SWEEPS="$AMG_MCGS_COARSE_SWEEPS" AMG_MCGS_OMEGA="$AMG_MCGS_OMEGA" AMG_MCGS_ORDER="$AMG_MCGS_ORDER" \
AMG_JACOBI_OMEGA="$AMG_JACOBI_OMEGA" AMG_JACOBI_FINE_SWEEPS="$AMG_JACOBI_FINE_SWEEPS" AMG_JACOBI_COARSE_SWEEPS="$AMG_JACOBI_COARSE_SWEEPS" AMG_CHEB_DEGREE="$AMG_CHEB_DEGREE" AMG_POWER_ITS="$AMG_POWER_ITS" AMG_LAMBDA_SAFETY="$AMG_LAMBDA_SAFETY" AMG_LAMBDA_LOW_FRACTION="$AMG_LAMBDA_LOW_FRACTION" AMG_SPECTRUM_POLICY="$AMG_SPECTRUM_POLICY" \
SST_G1=0 SST_G2=1 SST_G2_START=plug SST_G2_MAX="$SST_G2_MAX" SST_G2_PRINT_EVERY="$SST_G2_PRINT_EVERY" SST_G2_PLATEAU_TOL="$SST_G2_PLATEAU_TOL" SST_G2_PLATEAU_SAMPLES="$SST_G2_PLATEAU_SAMPLES" \
SST_INTENSITY="$SST_INTENSITY" SST_LENGTH_RATIO="$SST_LENGTH_RATIO" SST_ALPHA_K="$SST_ALPHA_K" SST_ALPHA_OMEGA="$SST_ALPHA_OMEGA" \
SST_LINEAR_RTOL="$SST_LINEAR_RTOL" SST_LINEAR_ATOL="$SST_LINEAR_ATOL" SST_LINEAR_MAX="$SST_LINEAR_MAX" SST_GS_OMEGA="$SST_GS_OMEGA" SST_K_FLOOR="$SST_K_FLOOR" SST_OMEGA_FLOOR="$SST_OMEGA_FLOOR" SST_WALL_PENALTY_GAMMA="$SST_WALL_PENALTY_GAMMA" SST_OMEGA_WALL_MODE="$SST_OMEGA_WALL_MODE" \
SST_OF_KAPPA="$SST_OF_KAPPA" SST_OF_E="$SST_OF_E" SST_OF_BETA1="$SST_OF_BETA1" SST_OF_RE_BLEND="$SST_OF_RE_BLEND" SST_OF_PRODUCTION="$SST_OF_PRODUCTION" SST_OF_PRODUCTION_SCALE="$SST_OF_PRODUCTION_SCALE" SST_OF_WALL_VOLUME_SCALE="$SST_OF_WALL_VOLUME_SCALE" SST_OF_PRODUCTION_LIMIT="$SST_OF_PRODUCTION_LIMIT" \
bash "$ROOT/RUN_HXT5B.sh"

LOG="$OUT/HXT5B_full_rans_fp32.log"
if [[ -f "$ROOT/CHECK_SST_G2_10D.py" ]]; then
  python3 "$ROOT/CHECK_SST_G2_10D.py" --log "$LOG"
fi

echo "SST_G2_500D_LOWY_TUNABLE_LOG=$LOG"
echo "SST_G2_500D_LOWY_TUNABLE_STATUS=PASS"
